[tool.semantic_release]
version_variable = "main.py:__version__"
version_toml = "pyproject.toml:tool.poetry.version"
upload_to_pypi = false
commit_parser = "angular" 
changelog_file = "CHANGELOG.md" 
