name: Release

on:
    push:
        branches:
            - main 
            - pull_request

jobs:
    release:
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.14.0"
            
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install semantic-release
            
            - name: Run semnatic-release
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                semantic-release version
                semantic-release changelog
                semantic-release publish

                
        

